---
on:
  - pull_request

jobs:
  python-deps:
    uses: ./.github/workflows/run_in_pyenv.yml
  linter-mypy:
    needs: [python-deps]
    uses: ./.github/workflows/run_in_pyenv.yml
    with:
      run_command: poetry run mypy .
  linter-ruff:
    needs: [python-deps]
    uses: ./.github/workflows/run_in_pyenv.yml
    with:
      run_command: poetry run ruff check --output-format=github .
  formatter-ruff:
    needs: [python-deps]
    uses: ./.github/workflows/run_in_pyenv.yml
    with:
      run_command: poetry run ruff format --check .
  tests-pytest:
    needs: [python-deps]
    uses: ./.github/workflows/run_in_pyenv.yml
    with:
      run_command: poetry run pytest -v --cov=. .
